### ISSUE TITLE
WebSocket error preventing gfms from starting

### ISSUE THREAD

**Issue by itslenny** [youurayy/gfms#38] opened 2017-05-01 07:25 UTC
I get the following error when I try starting gfms:

```
> gfms -n -p 888

.../node_modules/ws-rpc/lib/ws-rpc.js:43
        this.constructor.super_.apply(this, Array.prototype.slice.call(arguments));
                                ^

Class constructor WebSocketServer cannot be invoked without 'new' < ./$/ws-rpc/lib/ws-rpc.js(43) < ./$/gfms/gfms.js(18) < ./$/gfms/bin/gfms(3)
```

----

```
> node -v
v6.10.1
> npm info gfms version
0.0.12
```

**Comment by xiconet** [comment] 2017-05-11 01:57
Hi,
I have the same problem here on Win7, node v6.10.2
gfms version 0.0.12

**Comment by letientai299** [comment] 2017-05-20 06:07
Same issue

```sh
$› gfms --version
/home/john/.config/yarn/global/node_modules/ws-rpc/lib/ws-rpc.js:43
        this.constructor.super_.apply(this, Array.prototype.slice.call(arguments));
                                ^

Class constructor WebSocketServer cannot be invoked without 'new' < /home/john/.config/yarn/global/$/ws-rpc/lib/ws-rpc.js(43) < /home/john/.config/yarn/global/$/gfms/gfms.js(18) < /home/john/.config/yarn/global/$/gfms/bin/gfms(3)
```

```
$> node --version
v7.10.0
```

**Comment by dmelo** [comment] 2017-10-24 18:58
Same issue here:

```
/opt/node-v6.10.3-linux-x64/lib/node_modules/gfms/node_modules/ws-rpc/lib/ws-rpc.js:43
        this.constructor.super_.apply(this, Array.prototype.slice.call(arguments));
                                ^

Class constructor WebSocketServer cannot be invoked without 'new' < /opt/node-v6.10.3-linux-x64/lib/$/gfms/$/ws-rpc/lib/ws-rpc.js(43) < /opt/node-v6.10.3-linux-x64/lib/$/gfms/gfms.js(18) < /opt/node-v6.10.3-linux-x64/lib/$/gfms/bin/gfms(3)
```

**Comment by HarveyWilliams** [comment] 2017-12-14 17:03
## Temporary fix

This can be temporarily fixed by installing locally:

```
npm install gfms
```

You can then comment out the line (43) which is erroring (located in `/node_modules/gfms/node_modules/ws-rpc.js`):

```
...
var RPCWebSocketServer = function() {

        //this.constructor.super_.apply(this, Array.prototype.slice.call(arguments));

        this.rooms = new Object(null);
        ...
```

This line applies arguments/parameters/options to the server, but this package does not use any options and just uses the default setup.

You can then run the package:

```
node node_modules\gfms\gfms.js -p 8000
```

## WS RPC

The issue is on another package located here: https://github.com/youurayy/ws-rpc

I know what the offending line does but I don't know how it works. Might need a better JS ninja to figure it out.

**Closed** 2019-07-04 22:06 UTC
